### PR TITLE
updating to Unicode 15.1

### PR DESCRIPTION
**Pull request by lemire**
[Unicode 16 came out in September 2024](https://blog.unicode.org/2024/09/announcing-unicode-standard-version-160.html). We can update to it, but our tests cannot pass because IdnaTestV2 is still at Unicode 15. See https://github.com/web-platform-tests/wpt/pull/48301

However, we can try 15.1.0.

Previously, `"\u1E9E"` would map to double-s and it now maps to  `"xn--zca"`. I have added a test for this specific change. This is the change that triggers the failures in https://github.com/ada-url/ada/pull/794

### CODE REVIEW

**Comment by anonrig** [comment]
It seems the new changes are from Unicode 15.1

**Comment by lemire** [comment]
> It seems the new changes are from Unicode 15.1

Hmmm. Ok. Let us try.

**Comment by lemire** [comment]
@anonrig Please consider this PR. It might do what we need.

Note that we need to be careful when releasing because we are bumping the Unicode version which will definitively break some things for some people.

**Comment by anonrig** [comment]
> @anonrig Please consider this PR. It might do what we need.
> 
> Note that we need to be careful when releasing because we are bumping the Unicode version which will definitively break some things for some people.

We can release this version as as part of Ada v3.0. Since it's a major version, we might get away with any breakings due to the unicode bump

**Comment by anonrig** [comment]
@lemire it seems windows is unhappy

**Review by anonrig — APPROVED** [review]
Amazing work!

**Comment by lemire** [comment]
>  it seems windows is unhappy

I coded a workaround.

**Pull request merged**
